### ISSUE TITLE
Not implementing in gradle 

### ISSUE THREAD

**Issue by technoscope** [chirag-ji/DocuConverter#13]
hi i am trying to install this dependencies but its not working 
it give me this below error:
Failed to resolve: com.github.chirag-ji:DocuConverter:2.0.0
Show in Project Structure dialog
Affected Modules: app

**Comment by chirag-ji** [comment]
Hey, you need to add `jitpack `as maven repository source.

See: [https://jitpack.io/#chirag-ji/DocuConverter](How to add to maven)

**Comment by chirag-ji** [comment]
add it in your `settings.gradle`:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        ...
        maven { url 'https://jitpack.io' }
       ...
    }
}
```

And then it will start resolving
