### ISSUE TITLE
DocuConverter.jar giving error on compile

### ISSUE THREAD

**Issue by blazingdevil44** [chirag-ji/DocuConverter#2]
Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

When I compile app this error comes im a lil new please help

All I did was add jar file in libs folder in android project please help

This is my min and max api

applicationId "com.example.myapplication"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

it will be fix if I do minSdkVersion 26 but if I do that there be no point for converter since it will decrease range too much so does this docuConverter only works for latest smartphone ?

**Comment by chirag-ji** [comment]
The library is build on java 8, so it can not be used on android below API 26
