### ISSUE TITLE
Help i cant use this keep getting exception duplicates or error

### ISSUE THREAD

**Issue by blazingdevil44** [chirag-ji/DocuConverter#4]
Hi i am making a document reader simply i want to convert word, ppt to pdf and open excel but i cant seem to get it to work i have tried everything can you please help me i have been at it for week still no progress i even tried to copy all jar files from lib to my lib but still having problem specially when i try to convert to pdf

I am using android studio version : arctic fox
Can you give me a working code i will be forever in your debt
email: blazingdevil44@gmail.com

**Comment by chirag-ji** [comment]
Hey,

Could you share some more details or stacktrace of the error.

Thanks.

**Comment by chirag-ji** [comment]
Please try now, I've updated the release
it should work now

**Comment by chirag-ji** [comment]
Closing for no response
